JSON validation was failing for all outcomes, now fixed

diff --git a/.github/workflows/validate-mztab-stable.yml b/.github/workflows/validate-mztab-stable.yml
--- a/.github/workflows/validate-mztab-stable.yml
+++ b/.github/workflows/validate-mztab-stable.yml
@@ -318,10 +318,9 @@ jobs:
             fi
           done
           echo "Number of failed validations: $FAIL_COUNT"
-            if [ $FAIL_COUNT -ne 0 ]; then
-              echo "::error title=Validation summary::$FAIL_COUNT file(s) failed validation."
-              exit 1
-            fi
-            echo "::error title=Validation summary::$FAIL_COUNT file(s) failed validation."
-            exit 1
+          if [ $FAIL_COUNT -ne 0 ]; then
+             echo "::error title=Validation summary::$FAIL_COUNT file(s) failed validation."
+             exit 1
+          else
+             echo "All JSON files validated successfully."
           fi
